### ISSUE TITLE
Create_client error

### ISSUE THREAD

**Issue by PIKAPIKAR** [Black-Triangle-code/Telegram_coin_bot#6]
/Telegram_coin_bot$ python3 create_client.py 

Очередь аккаунта № 1
Входим в аккаунт: +770********
(*пишется пароль от аккаунта*)
Traceback (most recent call last):
  File "create_client.py", line 28, in <module>
    client.start()
AttributeError: 'TelegramClient' object has no attribute 'start'

И так в кажлм запуске, базу данных сделал без ошибок все прошло.

**Comment by PIKAPIKAR** [comment]
Входим в аккаунт: +770
*****
Please enter your phone (or bot token): 770
Traceback (most recent call last):
  File "create_client.py", line 28, in <module>
    client.start()
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/auth.py", line 132, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/auth.py", line 166, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/auth.py", line 475, in send_code_request
    phone, self.api_id, self.api_hash, types.CodeSettings()))
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)
И такая появляется пр первом запуске

**Comment by PIKAPIKAR** [comment]
Входим в аккаунт: +770
*****
Please enter your phone (or bot token): 770
Traceback (most recent call last):
  File "create_client.py", line 28, in <module>
    client.start()
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/auth.py", line 132, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/auth.py", line 166, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/auth.py", line 475, in send_code_request
    phone, self.api_id, self.api_hash, types.CodeSettings()))
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/home/siemens/.local/lib/python3.7/site-packages/telethon/client/users.py", line 77, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)
И такая появляется пр первом запуске

**Comment by PIKAPIKAR** [comment]
Нужно было получить апи на сайте, сразу не понял о чем речь
